services:
  pgsql:
    image: postgres:17.2
    hostname: pgsql
    container_name: kontact-pgsql
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: qPM0vE1Lz0G16q
      POSTGRES_PASSWORD: Nd85eQegsxBGC3OknxdJD9IO1ZL3IqAuzS29lOTg8EzpoNiyla
    ports:
      - "5432:5432"
    # networks:
    #   - kontact-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qPM0vE1Lz0G16q -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - pgsql:/var/lib/postgresql/data

#   next:
#     hostname: next
#     container_name: kontact-frontend
#     restart: always
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - express
#     networks:
#       - kontact-network

#   express:
#     hostname: express
#     container_name: kontact-express
#     restart: always
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     ports:
#       - "3001:3001"
#     depends_on:
#       pgsql:
#         condition: service_healthy
#     networks:
#       - kontact-network
#     env_file:
#       - backend/.env

# networks:
#   kontact-network:
#     driver: bridge

volumes:
  pgsql:
    name: kontact-web-next_pgsql
