services:
  pgsql:
    image: postgres:17.2-alpine
    restart: always
    container_name: kontact-pgsql
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - pgsql:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine
    restart: always
    container_name: kontact-redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis:/data

volumes:
  pgsql:
  redis: