import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./app.css";

const fontSans = Golos_Text({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "kontact web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${fontSans.className} antialiased`}>{children}</body>
    </html>
  );
}