import type { Metadata } from "next";
import { Golos_Text, Fira_Code } from "next/font/google";
import "./app.css";

const fontSans = Golos_Text({
  variable: "--font-sans",
  subsets: ['latin'],
});

const fontMono = Fira_Code({
  variable: "--font-mono",
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "kontact web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>{children}</body>
    </html>
  );
}