import { getChatList } from "@/actions/chat";
import AuthHeader from "@/components/AuthHeader";
import ChatList from "@/components/ChatList";
import { getAccount, getUser } from "@/lib/dal";
import { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getUser()
    const account = await getAccount()

    if (!user || !account) return null

    const chatList = await getChatList(user)

    return (
        <div className="flex h-screen">
            <div className="flex flex-col border-r border-r-neutral-200 max-w-[400px] w-full">
                <Suspense fallback={<Loading />}>
                    <AuthHeader authUser={user} authAccount={account} />
                    <ChatList items={chatList.map(({ id, firstName, lastName }) => ({ id, firstName, lastName  }))} />
                </Suspense>
            </div>
            {children}
        </div>
    );
}